# default config
[Common]
chainlink_node_funding = 0.1

[VRFv2]
[VRFv2.General]
use_existing_env = false
subscription_funding_amount_link = 5.0

cl_node_max_gas_price_gwei = 10
link_native_feed_response = 1000000000000000000
minimum_confirmations = 3

number_of_words = 3
callback_gas_limit = 1000000
max_gas_limit_coordinator_config = 2500000
fallback_wei_per_unit_link = 60000000000000000
staleness_seconds = 86400
gas_after_payment_calculation = 33825
fulfilment_flat_fee_link_ppm_tier_1 = 500
fulfilment_flat_fee_link_ppm_tier_2 = 500
fulfilment_flat_fee_link_ppm_tier_3 = 500
fulfilment_flat_fee_link_ppm_tier_4 = 500
fulfilment_flat_fee_link_ppm_tier_5 = 500
reqs_for_tier_2 = 0
reqs_for_tier_3 = 0
reqs_for_tier_4 = 0
reqs_for_tier_5 = 0
number_of_sub_to_create = 1
randomness_request_count_per_request = 1
randomness_request_count_per_request_deviation = 0
random_words_fulfilled_event_timeout = "2m"
wrapped_gas_overhead = 50000
coordinator_gas_overhead = 52000
wrapper_premium_percentage = 25
wrapper_max_number_of_words = 10
wrapper_consumer_funding_amount_native_token = 1.0
wrapper_consumer_funding_amount_link = 10

# VRF Job config
vrf_job_forwarding_allowed = false
vrf_job_estimate_gas_multiplier = 1.0
vrf_job_batch_fulfillment_enabled = false
vrf_job_batch_fulfillment_gas_multiplier = 1.15
vrf_job_poll_period = "1s"
vrf_job_request_timeout = "24h"

# BHS Job config
bhs_job_wait_blocks = 30
bhs_job_lookback_blocks = 250
bhs_job_poll_period = "1s"
bhs_job_run_timeout = "24h"


# PERFORMANCE test specific config

[VRFv2.ExistingEnv]
coordinator_address = "0x9Ff8b0fe6563288d6b43ca705268BD99DfD4d2bF"
consumer_address = ""
sub_id = 1
key_hash = "0x904d5d3a5fd0b02acc61c7a16773cbb9342e30979766972ef9e90fc6e11b4415"
create_fund_subs_and_add_consumers = true
link_address = "0xCf989972eec71939D6BA98c0E2BB04A647b68190"
node_sending_key_funding_min = 10
node_sending_keys = [
    "0x4096CeEC6590725fA30cAf93826728A00a0E91ab",
    "0xB3f4B3F0A83126157FcC482C5d183f0fBF005ee5",
    "0xdBA0C98cf907DAA4243487817A642313977Cd971"
]

[VRFv2.Common]
cancel_subs_after_test_run = true

#SOAK TEST CONFIG
[SOAK.Common]
chainlink_node_funding = 0.1

[SOAK.VRFv2.General]
randomness_request_count_per_request = 1 # amount of randomness requests to make per one TX request
randomness_request_count_per_request_deviation = 0 #NOTE - deviation should be less than randomness_request_count_per_request setting
number_of_sub_to_create = 1
subscription_funding_amount_link = 5.0

[SOAK.VRFv2.Performance]
test_duration = "1m"
rate_limit_unit_duration = "3s"
rps = 1

# LOAD TEST CONFIG
[Load.Common]
chainlink_node_funding = 0.1

[Load.VRFv2.General]
randomness_request_count_per_request = 3 # amount of randomness requests to make per one TX request
randomness_request_count_per_request_deviation = 2 #NOTE - deviation should be less than randomness_request_count_per_request setting
number_of_sub_to_create = 1
subscription_funding_amount_link = 5.0

[Load.VRFv2.Performance]
test_duration = "2m"
rate_limit_unit_duration = "3s"
rps = 1


# STRESS TEST CONFIG
[Stress.Common]
chainlink_node_funding = 0.1

[Stress.VRFv2.General]
randomness_request_count_per_request = 3 # amount of randomness requests to make per one TX request
randomness_request_count_per_request_deviation = 2 #NOTE - deviation should be less than randomness_request_count_per_request setting
number_of_sub_to_create = 1
subscription_funding_amount_link = 5.0

[Stress.VRFv2.Performance]
test_duration = "2m"
rate_limit_unit_duration = "3s"
rps = 1
